@startuml
'https://plantuml.com/class-diagram

class Message
class Key

abstract AbstractCollection
interface List
interface Collection

List <|-- AbstractList
Collection <|-- AbstractCollection

Collection <|- List
AbstractCollection <|- AbstractList
Message --> Key

class Message {
int id
String body
int sentBy
Key requiredKey
}

class Key{
String name
String value
}

enum TimeUnit {
DAYS
HOURS
MINUTES
}

@enduml