@startuml
'https://plantuml.com/class-diagram

class User
class Conversation

class StartConversationDataAccessObject


interface StartConversationDataAccessInterface
interface StartConversationInputBoundary
interface StartConversationOuputBoundary
class StartConversationOutputData
class StartConversationInputData
class StartConversationInteractor

class StartConversationController
class StartConversationPresenter
class StartConversationViewModel
class StartConversationView



StartConversationInteractor -|> StartConversationInputBoundary
StartConversationPresenter -|> StartConversationOuputBoundary
StartConversationDataAccessObject -|> StartConversationDataAccessInterface

StartConversationInteractor --> StartConversationOuputBoundary
StartConversationInteractor --> StartConversationInputData
StartConversationInteractor --> StartConversationOutputData
StartConversationInteractor --> StartConversationDataAccessInterface

StartConversationController --> StartConversationInputData
StartConversationController --> StartConversationInputBoundary
StartConversationPresenter --> StartConversationOutputData
StartConversationPresenter --> StartConversationViewModel

StartConversationView --> StartConversationViewModel
StartConversationView --> StartConversationController

StartConversationView --> StartconversationViewModel
StartConversationPresenter --> StartConversationViewModel

StartConversationInteractor --> User
StartConversationDataAccessInterface --> User

User --> Conversation

Conversation --> Key
Conversation --> Message



class User {
int id
String name
String email
ArrayList<int> conversations
}

class Conversation{
int id
String name
Key requiredKey
ArrayList<Message> messages
}

class Key{
String name
String value
}

class Message{
int id
String body
}



@enduml